import { defineConfig } from "astro/config";
import node from "@astrojs/node";
import varlock from "@varlock/astro-integration";

// On-demand rendering (SSR) is required: the OAuth flow reads/sets cookies and
// fetches per-user data at request time. The Node adapter (standalone) gives a
// real server to run the app — and the E2E suite — against.
//
// Varlock validates env against `.env.schema`, redacts @sensitive values, and
// exposes `ENV` from `varlock/env`; types are generated by the `typegen` task.
export default defineConfig({
  output: `server`,
  adapter: node({ mode: `standalone` }),
  integrations: [varlock()]
});
