catalog:
  "@tanstack/react-query": ^5.100.14
  "@types/node": ^25.9.1
  "@types/react": ^19.2.15
  "@types/react-dom": ^19.2.3
  kkrpc: ^2.0.0
  koffi: ^3.0.2
  react: ^19.2.6
  react-dom: ^19.2.6
  signal-polyfill: ^0.2.2
  type-fest: ^5.6.0
  typescript: ^6.0.3
  valibot: ^1.4.0
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vite-plus: latest
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.16.0.cjs
