catalog:
  "@napi-rs/keyring": ^1.3.0
  "@playwright/test": ^1.60.0
  "@tailwindcss/postcss": ^4.3.1
  "@tailwindcss/vite": ^4.3.1
  "@tsdown/exe": ^0.22.3
  "@tanstack/react-query": ^5.101.0
  "@tanstack/react-query-devtools": ^5.101.0
  "@tauri-apps/api": ^2.11.0
  "@tauri-apps/cli": ^2.11.2
  "@tauri-apps/plugin-shell": ^2.3.5
  "@types/node": ^25.9.3
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@varlock/nextjs-integration": ^1.1.3
  "@vitejs/plugin-react": ^6.0.2
  "@xstate/react": ^6.1.0
  disposablestack: ^1.1.8
  jose: ^6.2.3
  kkrpc: ^2.0.0
  koffi: ^3.0.2
  lucide-react: ^1.17.0
  msw: ^2.14.6
  next: ^16.2.9
  postcss: ^8.5.15
  react: ^19.2.7
  react-aria-components: ^1.18.0
  react-dom: ^19.2.7
  signal-polyfill: ^0.2.2
  tailwindcss: ^4.3.1
  tauri-plugin-keyring-api: ^0.1.1
  typescript: ^6.0.3
  valibot: ^1.4.1
  valimock: 1.6.0
  varlock: ^1.6.1
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vite-plus: latest
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"
  xstate: ^5.32.1

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.16.0.cjs
