import { defineConfig } from "vite-plus";
import { lint, fmt, mergeLint } from "@saeris/configs";

export default defineConfig({
  run: {
    tasks: {
      build: { command: `vp run -r build`, cache: true },
      "build:apps": { command: `vp run -r build:apps`, cache: true },
      "build:examples": { command: `vp run -r build:examples`, cache: true },
      "build:all": {
        command: `vp run build && vp run build:apps && vp run build:examples`,
        cache: true
      },
      lint: { command: `vp lint`, cache: true },
      // Run every package's `typegen` task (e.g. the examples' Varlock
      // `env.d.ts`). New packages with a `typegen` task are picked up
      // automatically. `vp check`/`vp test` resolve workspace source via the
      // `@discordkit/source` condition, but the examples' generated env types
      // must exist for the typecheck to pass.
      typegen: { command: `vp run -r typegen`, cache: false },
      // Cleanup is split by artifact class (mirroring the build:* tasks) so a
      // scenario can clear just what it produced. rimraf globs are platform-
      // agnostic. Each subset is independent; `clean` runs all three.
      //
      // Throwaway test/run output — safe to nuke anytime (e.g. after E2E).
      // Notably does NOT touch package dist, so resetting post-E2E won't force
      // a full package rebuild. The `e2e.sqlite*` files are the Better Auth
      // example's throwaway E2E database (recreated each run).
      "clean:test": {
        command: `rimraf --glob "examples/*/test-results" "examples/*/playwright-report" "examples/*/blob-report" ".playwright-mcp" "coverage" "examples/*/e2e.sqlite*"`,
        cache: false
      },
      // Example build output + generated codegen (regenerated by each example's
      // build/typegen). Leaves package dist intact. `better-auth.sqlite*` is the
      // Better Auth example's local dev database (recreated on next dev start by
      // the startup migration).
      "clean:examples": {
        command: `rimraf --glob "examples/*/dist" "examples/*/.next" "examples/*/.astro" "examples/*/.output" "examples/*/env.d.ts" "examples/*/better-auth.sqlite*"`,
        cache: false
      },
      // Published-package build output — expensive to regenerate; cleaned only
      // by the nuclear `clean`.
      "clean:dist": {
        command: `rimraf --glob "packages/*/dist"`,
        cache: false
      },
      // Everything: package dist + example builds + throwaway output.
      clean: {
        command: `vp run clean:test && vp run clean:examples && vp run clean:dist`,
        cache: false
      },
      dev: { command: `vp run -r --parallel dev`, cache: false },
      // Run every example's `e2e` task (each boots its own server with Discord
      // mocked and drives the shared @discordkit/e2e flow via Playwright). New
      // example apps are picked up automatically once they define an `e2e` task.
      // The examples resolve @discordkit/* to dist, so build the packages first.
      // Sequence build BEFORE the recursive e2e in the command itself, not via
      // `dependsOn`: the examples resolve @discordkit/* to dist at their Next
      // server runtime, so the packages must be fully built first. A
      // `dependsOn: [build]` doesn't enforce that here because the command is a
      // nested `vp run -r e2e` (its own task graph), which would race the
      // still-running build. `&&` guarantees the ordering across that boundary.
      e2e: { command: `vp run build && vp run -r e2e`, cache: false },
      ci: { command: `vp lint && vp test && vp run build:all`, cache: false }
    }
  },
  // Resolve workspace packages to their TypeScript source via the private
  // `@discordkit/source` export condition (matches tsconfig `customConditions`)
  // so Vitest runs against `src/` without requiring a build. The name is
  // private — not `development` — so external bundlers (Next.js) don't pick it
  // up and try to resolve our `.js`-on-`.ts` source imports, which they can't.
  resolve: {
    conditions: [`@discordkit/source`]
  },
  test: {
    name: `discordkit`,
    globals: true,
    watch: false,
    // Node is ~2x faster than happy-dom for this suite (13s vs 26s wall-clock).
    // No test in this codebase touches DOM APIs that Node 18+ doesn't already
    // provide globally (Response, URL, Blob, File, FormData, crypto.subtle).
    // verifyKey.ts feature-detects `typeof window` so it works in both
    // environments. If a future test needs a real DOM, opt in per-file with:
    //   // @vitest-environment happy-dom
    environment: `node`,
    coverage: {
      provider: `v8`
    },
    // Exclude Claude Code agent worktrees from test discovery. Each agent
    // run materializes a full git worktree under `.claude/worktrees/`,
    // including its own copy of every spec file. Without this exclusion,
    // Wallaby/vitest pick up the duplicated specs and report them as
    // failing/passing alongside the canonical ones.
    exclude: [
      `**/node_modules/**`,
      `**/dist/**`,
      `**/.{idea,git,cache,output,temp}/**`,
      `**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*`,
      `**/.claude/**`,
      // Playwright E2E specs (examples/*/e2e/**) import @playwright/test and
      // run under the Playwright runner, not Vitest. Keep them out of the unit
      // test discovery.
      `**/e2e/**`
    ]
  },
  lint: mergeLint(lint, {
    rules: {
      // False-positive on type-only namespace members like `v.InferOutput`.
      // The rule reads the runtime JS bundle rather than the .d.ts, so
      // pure-type re-exports are reported as missing. TypeScript already
      // catches truly-missing members. Tracked at oxc-project/oxc#13258.
      "import/namespace": `off`
    },
    overrides: [
      {
        // `.test-d.ts` files use vitest's `assertType<T>` + `@ts-expect-error`
        // for compile-time assertions; they don't use runtime `expect()`.
        // The shared `vitest` preset's `expect-expect` rule allows
        // `["expect", "expect*"]` only, so these files trip the rule even
        // though they contain the right kind of assertions.
        files: [`**/*.test-d.{ts,tsx}`],
        rules: {
          "vitest/expect-expect": `off`
        }
      },
      {
        // `scripts/` holds one-off codemods and doc-tooling — not shipped
        // library surface. Defensive optional chains, type-coerce casts,
        // and structural narrowing patterns are appropriate here even when
        // tsc can prove them locally redundant.
        files: [`scripts/**/*.{js,jsx,ts,tsx}`],
        rules: {
          "typescript/no-unsafe-type-assertion": `off`,
          "typescript/no-unnecessary-condition": `off`
        }
      },
      {
        // Schema-definition and request-helper files use `as v.GenericSchema<T>`
        // (and `as v.ObjectSchema<...>` / `as v.RecordSchema<...>`) casts to
        // constrain the function return type to the published shape. Casts ARE
        // redundant at the type-checker level — that's exactly what we want,
        // because forcing the published type to GenericSchema<T> stops
        // downstream .d.ts files from re-inlining the full entries map at
        // every reference. Removing them works at the type level but bloats
        // the .d.ts in practice. The rules have no way to know about emit-
        // shape concerns. Both `no-unsafe-type-assertion` and
        // `no-unnecessary-type-assertion` flag these; the autofixer for the
        // latter silently strips them, breaking the published types. We
        // disable both project-wide in `packages/{core,client}/src` since
        // those directories are entirely schema-defining surface — a real
        // unsafe-cast there would be type-checked anyway.
        files: [`packages/core/src/**/*.ts`, `packages/client/src/**/*.ts`],
        rules: {
          "typescript/no-unsafe-type-assertion": `off`,
          "typescript/no-unnecessary-type-assertion": `off`
        }
      },
      {
        // `throw redirect(...)` is TanStack Router's documented control-flow API
        // (redirect() returns a throwable), not an error-handling antipattern.
        // (The `next` lint fragment is applied per-Next-example now, not
        // workspace-wide, so no Next-rule exceptions are needed here.)
        files: [`examples/with-tanstack-start/**/*.{ts,tsx}`],
        rules: {
          "typescript/only-throw-error": `off`
        }
      },
      {
        // TanStack Start route modules and the custom server entry export a
        // `default` by framework contract (TanStack's file-router and
        // server-entry APIs consume the default export). The shared `imports`
        // fragment only exempts Next's `app/`/`pages/`/`middleware` paths, so
        // grant the same exemption for TanStack's equivalents here. Scoped to
        // just these files so accidental default exports in lib code still warn.
        files: [
          `examples/with-tanstack-start/src/routes/**/*.{ts,tsx}`,
          `examples/with-tanstack-start/src/server.ts`,
          `examples/with-tanstack-start/src/router.tsx`
        ],
        rules: {
          "import/no-default-export": `off`,
          "import/no-anonymous-default-export": `off`
        }
      }
    ]
  }),
  fmt
});
