import { z } from "zod";
import { stickerSchema } from "../../sticker/types/Sticker";
import { applicationSchema } from "../../application/types/Application";
import { reactionSchema } from "./Reaction";
import { memberSchema } from "../../guild/types/Member";
import { userSchema } from "../../user/types/User";
import { channelSchema } from "./Channel";
import { interactionTypeSchema } from "./InteractionType";
import { messageActivitySchema } from "./MessageActivity";
import { channelMentionSchema } from "./ChannelMention";
import { embedSchema } from "./Embed";
import { messageReferenceSchema } from "./MessageReference";
import { attachmentSchema } from "./Attachment";
import { messageFlagSchema } from "./MessageFlag";

const baseMessageSchema = z.object({
  /** id of the message */
  id: z.string(),
  /** id of the channel the message was sent in */
  channelId: z.string(),
  /** user object	the author of this message (not guaranteed to be a valid user, see below) */
  author: userSchema.optional(),
  /** contents of the message */
  content: z.string(),
  /** when this message was sent */
  timestamp: z.string(),
  /** when this message was edited (or null if never) */
  editedTimestamp: z.string().optional(),
  /** whether this was a TTS message */
  tts: z.boolean(),
  /** whether this message mentions everyone */
  mentionEveryone: z.boolean(),
  /** users specifically mentioned in the message */
  mentions: userSchema.array(),
  /** roles specifically mentioned in this message */
  mentionRoles: z.string().array(),
  /** channels specifically mentioned in this message */
  mentionChannels: channelMentionSchema.array().optional(),
  /** any attached files */
  attachments: attachmentSchema.array().optional(),
  /** any embedded content */
  embeds: embedSchema.array().optional(),
  /** reactions to the message */
  reactions: reactionSchema.array().optional(),
  /** used for validating a message was sent */
  nonce: z.union([z.number(), z.string()]).optional(),
  /** whether this message is pinned */
  pinned: z.boolean(),
  /** if the message is generated by a webhook, this is the webhook's id */
  webhookId: z.string(),
  /** type of message */
  type: z.number(),
  /** sent with Rich Presence-related chat embeds */
  activity: messageActivitySchema.optional(),
  /** sent with Rich Presence-related chat embeds */
  application: applicationSchema.optional(),
  /** if the message is an Interaction or application-owned webhook, this is the id of the application */
  applicationId: z.string().optional(),
  /** data showing the source of a crosspost, channel follow add, pin, or reply message */
  messageReference: messageReferenceSchema.optional(),
  /** message flags combined as a bitfield */
  flags: messageFlagSchema.optional(),
  /** sent if the message is a response to an Interaction */
  interaction: z
    .object({
      /** id of the interaction */
      id: z.string(),
      /** the type of interaction */
      type: interactionTypeSchema,
      /** the name of the application command */
      name: z.string(),
      /** the user who invoked the interaction */
      user: userSchema.partial(),
      /** the member who invoked the interaction in the guild */
      member: memberSchema.partial().optional()
    })
    .optional(),
  /** the thread that was started from this message, includes thread member object */
  thread: channelSchema.optional(),
  /** sent if the message contains components like buttons, action rows, or other interactive components */
  //components?: MessageComponent[];
  /** sent if the message contains stickers */
  stickerItems: stickerSchema.array().optional()
});

export const messageSchema = baseMessageSchema.extend({
  /** the message associated with the message_reference */
  referencedMessage: z.lazy(() => baseMessageSchema).optional()
});

export type Message = z.infer<typeof messageSchema>;
