import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TrpcProvider } from "./providers";
import "./globals.css";

/* eslint-disable @stylistic/quotes */
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
/* eslint-enable @stylistic/quotes */

const RootLayout: React.FC<{ readonly children: React.ReactNode }> = ({
  children
}) => (
  <TrpcProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  </TrpcProvider>
);

export default RootLayout;
