import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/**
 * The app's router factory. TanStack Start's server handler looks for an
 * exported `getRouter` to build a fresh router per request. `routeTree` is
 * generated by the TanStack Start vite plugin from the files in `src/routes`.
 */
export function getRouter(): ReturnType<typeof createRouter> {
  return createRouter({
    routeTree,
    scrollRestoration: true
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
