// https://discord.com/developers/docs/events/gateway#gateway-intents

import { bitfield } from "@discordkit/core/validations/bitfield";
import * as v from "valibot";

/**
 * ### [Gateway Intents](https://discord.com/developers/docs/events/gateway#gateway-intents)
 *
 * Bitwise values passed as `intents` when identifying. An intent you don't
 * request means you receive **none** of its events.
 *
 * Three intents are **privileged** and must be enabled for your app in the
 * Developer Portal (and approved after verification for apps in 100+ guilds):
 * `GUILD_PRESENCES`, `GUILD_MEMBERS`, and `MESSAGE_CONTENT`. Requesting one
 * you haven't been granted closes the connection with
 * {@link GatewayCloseCode.DISALLOWED_INTENTS | 4014}.
 */
export const GatewayIntents = {
  /** Gates: GUILD_CREATE, GUILD_UPDATE, GUILD_DELETE, GUILD_ROLE_CREATE, GUILD_ROLE_UPDATE, GUILD_ROLE_DELETE, CHANNEL_CREATE, CHANNEL_UPDATE, CHANNEL_DELETE, CHANNEL_PINS_UPDATE, THREAD_CREATE, THREAD_UPDATE, THREAD_DELETE, THREAD_LIST_SYNC, THREAD_MEMBER_UPDATE, THREAD_MEMBERS_UPDATE, STAGE_INSTANCE_CREATE, STAGE_INSTANCE_UPDATE, STAGE_INSTANCE_DELETE, VOICE_CHANNEL_STATUS_UPDATE, VOICE_CHANNEL_START_TIME_UPDATE. */
  GUILDS: 1 << 0,
  /** **Privileged** — must be enabled in the Developer Portal. Gates: GUILD_MEMBER_ADD, GUILD_MEMBER_UPDATE, GUILD_MEMBER_REMOVE, THREAD_MEMBERS_UPDATE. */
  GUILD_MEMBERS: 1 << 1,
  /** Gates: GUILD_AUDIT_LOG_ENTRY_CREATE, GUILD_BAN_ADD, GUILD_BAN_REMOVE. */
  GUILD_MODERATION: 1 << 2,
  /** Gates: GUILD_EMOJIS_UPDATE, GUILD_STICKERS_UPDATE, GUILD_SOUNDBOARD_SOUND_CREATE, GUILD_SOUNDBOARD_SOUND_UPDATE, GUILD_SOUNDBOARD_SOUND_DELETE, GUILD_SOUNDBOARD_SOUNDS_UPDATE. */
  GUILD_EXPRESSIONS: 1 << 3,
  /** Gates: GUILD_INTEGRATIONS_UPDATE, INTEGRATION_CREATE, INTEGRATION_UPDATE, INTEGRATION_DELETE. */
  GUILD_INTEGRATIONS: 1 << 4,
  /** Gates: WEBHOOKS_UPDATE. */
  GUILD_WEBHOOKS: 1 << 5,
  /** Gates: INVITE_CREATE, INVITE_DELETE. */
  GUILD_INVITES: 1 << 6,
  /** Gates: VOICE_CHANNEL_EFFECT_SEND, VOICE_STATE_UPDATE. */
  GUILD_VOICE_STATES: 1 << 7,
  /** **Privileged** — must be enabled in the Developer Portal. Gates: PRESENCE_UPDATE. */
  GUILD_PRESENCES: 1 << 8,
  /** Gates: MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, MESSAGE_DELETE_BULK. */
  GUILD_MESSAGES: 1 << 9,
  /** Gates: MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI. */
  GUILD_MESSAGE_REACTIONS: 1 << 10,
  /** Gates: TYPING_START. */
  GUILD_MESSAGE_TYPING: 1 << 11,
  /** Gates: MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, CHANNEL_PINS_UPDATE. */
  DIRECT_MESSAGES: 1 << 12,
  /** Gates: MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI. */
  DIRECT_MESSAGE_REACTIONS: 1 << 13,
  /** Gates: TYPING_START. */
  DIRECT_MESSAGE_TYPING: 1 << 14,
  /** **Privileged** — must be enabled in the Developer Portal. Gates message *fields* (`content`, `embeds`, `attachments`, `components`, `poll`) rather than whole events. */
  MESSAGE_CONTENT: 1 << 15,
  /** Gates: GUILD_SCHEDULED_EVENT_CREATE, GUILD_SCHEDULED_EVENT_UPDATE, GUILD_SCHEDULED_EVENT_DELETE, GUILD_SCHEDULED_EVENT_USER_ADD, GUILD_SCHEDULED_EVENT_USER_REMOVE. */
  GUILD_SCHEDULED_EVENTS: 1 << 16,
  /** Gates: AUTO_MODERATION_RULE_CREATE, AUTO_MODERATION_RULE_UPDATE, AUTO_MODERATION_RULE_DELETE. */
  AUTO_MODERATION_CONFIGURATION: 1 << 20,
  /** Gates: AUTO_MODERATION_ACTION_EXECUTION. */
  AUTO_MODERATION_EXECUTION: 1 << 21,
  /** Gates: MESSAGE_POLL_VOTE_ADD, MESSAGE_POLL_VOTE_REMOVE. */
  GUILD_MESSAGE_POLLS: 1 << 24,
  /** Gates: MESSAGE_POLL_VOTE_ADD, MESSAGE_POLL_VOTE_REMOVE. */
  DIRECT_MESSAGE_POLLS: 1 << 25
} as const;

/**
 * ### [Gateway Intents](https://discord.com/developers/docs/events/gateway#gateway-intents)
 */
export const gatewayIntentsSchema = v.enum_(GatewayIntents);
export const gatewayIntent = bitfield(
  `gatewayIntent`,
  GatewayIntents,
  `Invalid Gateway Intent`
);

/** A single intent's name. */
export type GatewayIntentName = keyof typeof GatewayIntents;

/**
 * The privileged intents. Requesting one your app hasn't been granted is a
 * connection-fatal `4014`, so these are worth surfacing distinctly.
 */
export const PRIVILEGED_INTENTS = [
  `GUILD_PRESENCES`,
  `GUILD_MEMBERS`,
  `MESSAGE_CONTENT`
] as const satisfies readonly GatewayIntentName[];

/**
 * Which intents gate each dispatch event, generated from the docs' intent list.
 *
 * Events absent from this map are never gated — Discord always delivers them.
 * An event listed under two intents (the DM/guild message pairs) arrives if
 * *either* is requested.
 */
export const EVENT_INTENTS = {
  AUTO_MODERATION_ACTION_EXECUTION: [`AUTO_MODERATION_EXECUTION`],
  AUTO_MODERATION_RULE_CREATE: [`AUTO_MODERATION_CONFIGURATION`],
  AUTO_MODERATION_RULE_DELETE: [`AUTO_MODERATION_CONFIGURATION`],
  AUTO_MODERATION_RULE_UPDATE: [`AUTO_MODERATION_CONFIGURATION`],
  CHANNEL_CREATE: [`GUILDS`],
  CHANNEL_DELETE: [`GUILDS`],
  CHANNEL_PINS_UPDATE: [`GUILDS`, `DIRECT_MESSAGES`],
  CHANNEL_UPDATE: [`GUILDS`],
  GUILD_AUDIT_LOG_ENTRY_CREATE: [`GUILD_MODERATION`],
  GUILD_BAN_ADD: [`GUILD_MODERATION`],
  GUILD_BAN_REMOVE: [`GUILD_MODERATION`],
  GUILD_CREATE: [`GUILDS`],
  GUILD_DELETE: [`GUILDS`],
  GUILD_EMOJIS_UPDATE: [`GUILD_EXPRESSIONS`],
  GUILD_INTEGRATIONS_UPDATE: [`GUILD_INTEGRATIONS`],
  GUILD_MEMBER_ADD: [`GUILD_MEMBERS`],
  GUILD_MEMBER_REMOVE: [`GUILD_MEMBERS`],
  GUILD_MEMBER_UPDATE: [`GUILD_MEMBERS`],
  GUILD_ROLE_CREATE: [`GUILDS`],
  GUILD_ROLE_DELETE: [`GUILDS`],
  GUILD_ROLE_UPDATE: [`GUILDS`],
  GUILD_SCHEDULED_EVENT_CREATE: [`GUILD_SCHEDULED_EVENTS`],
  GUILD_SCHEDULED_EVENT_DELETE: [`GUILD_SCHEDULED_EVENTS`],
  GUILD_SCHEDULED_EVENT_UPDATE: [`GUILD_SCHEDULED_EVENTS`],
  GUILD_SCHEDULED_EVENT_USER_ADD: [`GUILD_SCHEDULED_EVENTS`],
  GUILD_SCHEDULED_EVENT_USER_REMOVE: [`GUILD_SCHEDULED_EVENTS`],
  GUILD_SOUNDBOARD_SOUND_CREATE: [`GUILD_EXPRESSIONS`],
  GUILD_SOUNDBOARD_SOUND_DELETE: [`GUILD_EXPRESSIONS`],
  GUILD_SOUNDBOARD_SOUND_UPDATE: [`GUILD_EXPRESSIONS`],
  GUILD_SOUNDBOARD_SOUNDS_UPDATE: [`GUILD_EXPRESSIONS`],
  GUILD_STICKERS_UPDATE: [`GUILD_EXPRESSIONS`],
  GUILD_UPDATE: [`GUILDS`],
  INTEGRATION_CREATE: [`GUILD_INTEGRATIONS`],
  INTEGRATION_DELETE: [`GUILD_INTEGRATIONS`],
  INTEGRATION_UPDATE: [`GUILD_INTEGRATIONS`],
  INVITE_CREATE: [`GUILD_INVITES`],
  INVITE_DELETE: [`GUILD_INVITES`],
  MESSAGE_CREATE: [`GUILD_MESSAGES`, `DIRECT_MESSAGES`],
  MESSAGE_DELETE: [`GUILD_MESSAGES`, `DIRECT_MESSAGES`],
  MESSAGE_DELETE_BULK: [`GUILD_MESSAGES`],
  MESSAGE_POLL_VOTE_ADD: [`GUILD_MESSAGE_POLLS`, `DIRECT_MESSAGE_POLLS`],
  MESSAGE_POLL_VOTE_REMOVE: [`GUILD_MESSAGE_POLLS`, `DIRECT_MESSAGE_POLLS`],
  MESSAGE_REACTION_ADD: [`GUILD_MESSAGE_REACTIONS`, `DIRECT_MESSAGE_REACTIONS`],
  MESSAGE_REACTION_REMOVE: [
    `GUILD_MESSAGE_REACTIONS`,
    `DIRECT_MESSAGE_REACTIONS`
  ],
  MESSAGE_REACTION_REMOVE_ALL: [
    `GUILD_MESSAGE_REACTIONS`,
    `DIRECT_MESSAGE_REACTIONS`
  ],
  MESSAGE_REACTION_REMOVE_EMOJI: [
    `GUILD_MESSAGE_REACTIONS`,
    `DIRECT_MESSAGE_REACTIONS`
  ],
  MESSAGE_UPDATE: [`GUILD_MESSAGES`, `DIRECT_MESSAGES`],
  PRESENCE_UPDATE: [`GUILD_PRESENCES`],
  STAGE_INSTANCE_CREATE: [`GUILDS`],
  STAGE_INSTANCE_DELETE: [`GUILDS`],
  STAGE_INSTANCE_UPDATE: [`GUILDS`],
  THREAD_CREATE: [`GUILDS`],
  THREAD_DELETE: [`GUILDS`],
  THREAD_LIST_SYNC: [`GUILDS`],
  THREAD_MEMBER_UPDATE: [`GUILDS`],
  THREAD_MEMBERS_UPDATE: [`GUILDS`, `GUILD_MEMBERS`],
  THREAD_UPDATE: [`GUILDS`],
  TYPING_START: [`GUILD_MESSAGE_TYPING`, `DIRECT_MESSAGE_TYPING`],
  VOICE_CHANNEL_EFFECT_SEND: [`GUILD_VOICE_STATES`],
  VOICE_CHANNEL_START_TIME_UPDATE: [`GUILDS`],
  VOICE_CHANNEL_STATUS_UPDATE: [`GUILDS`],
  VOICE_STATE_UPDATE: [`GUILD_VOICE_STATES`],
  WEBHOOKS_UPDATE: [`GUILD_WEBHOOKS`]
} as const satisfies Record<string, readonly GatewayIntentName[]>;

/** Combine intents into the bitfield sent in an `IDENTIFY` payload. */
export const intents = (...names: readonly GatewayIntentName[]): number =>
  names.reduce((mask, name) => mask | GatewayIntents[name], 0);
